// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctnnjsnuntweqpcljxuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0bm5qc251bnR3ZXFwY2xqeHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTM5ODAsImV4cCI6MjA2NzQ4OTk4MH0.OszWCJacjv4lnefrc0JoMX6JfUJkGTEMu8nSKeyifyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});